SRC += leds.c

LTO_ENABLE = yes
AVR_USE_MINIMAL_PRINTF = yes

SERIAL_DRIVER = bitbang
#CONSOLE_ENABLE=yes

#RGB_MATRIX_ENABLE = yes
# RGB_MATRIX_DRIVER = ws2812
# WS2812_DRIVER = bitbang

#AUDIO_ENABLE = yes
UNICODEMAP_ENABLE = yes
